services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_db 
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres
    ports:
      - "37574:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql       # <-- PG18+: монтируем родительскую директорию
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      # в docker-compose.yml, в секцию postgres: